FROM debian:stable-slim
RUN apt-get update && apt-get install -y curl --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir -p /home/ubuntu/.claude \
    && chown -R 1000:1000 /home/ubuntu
